### ISSUE TITLE
Contrib Source

### ISSUE THREAD

**Issue by simeonwillbanks** [glean/glean#7]
Why don't we use Glean to power the Contrib [Source](https://github.com/glean/glean#sources)? :smile:

We could create https://github.com/glean/glean-contrib; it would reference contrib sources.

_Potential Contrib Repo Structure_

```
lagalaxy/trophies.toml
iptccodes.toml
```

_Potential Contrib Repo Files_

``` toml
# lagalaxy/roster.toml
identifier = "lagalaxy/trophies"
name = "lagalaxy: trophies"
description = "All trophies won by the LA Galaxy"
```

``` toml
# iptccodes.toml
identifier = "simeonwillbanks/iptccodes"
name = "iptccodes"
description = "Metadata Taxonomies for News"
```

```
❯ glean search --contrib
iptccodes -- Metadata Taxonomies for News
lagalaxy: trophies -- All trophies won by the LA Galaxy
```

Thanks for considering!
